### ISSUE TITLE
Question about matching matrix M2

### ISSUE THREAD

**Issue by canjiali** [yangliuy/NeuralResponseRanking#2]
Hi, thanks for the nice work. I have one question. In the paper, the matching matrix M1 is fed into a BiGRU layer to learning the hidden representation. However, the expanded W terms in PRF are appended to the original query in your method and these terms are unigram terms thus may not have sequential meaning themselves or with the original query, does it make sense to apply a BiGRU layer on top of M1??

**Comment by yangliuy** [comment]
Thank you for your question!

In the paper, M1 is computed based on the dot product similarity of word embeddings of word pairs in two sequences. What you mentioned is actually M2 in the paper. You are right. For the expanded part of the response, the sequential information may be not very useful. However, note that the majority part of an expanded response is still the previous terms in the original response. That's why the output of BiGRU could be still useful to capture the dependency information between terms. As shown in our experiments in Section 4.4, M1 is more important than M2. But adding the matching patterns in M2 could also help improve the performance.

**Comment by canjiali** [comment]
Aha, in traditional PRF methods, each term only appears once in the reformed query.  This one looks different. Glad to see the effectiveness of BiGRU here!
